import './js/hero'
import './js/recipes-list'
//import './js/popular-recipes'
import './js/filter'
import './js/pagination'
import './js/scroll-to-top'
import './js/theme-switcher'
import './js/mobMenu'